provider "aws" {
  region = "ap-south-1"
}

# Resource configuration for existing S3 bucket
# This should match the existing bucket's configuration
resource "aws_s3_bucket" "existing_bucket" {
  bucket = "existing-bucket-name"  # Replace with actual bucket name
  
  tags = {
    Name        = "Imported Bucket"
    Environment = "Production"
    ManagedBy   = "Terraform"
  }
}

# Resource configuration for existing EC2 instance
resource "aws_instance" "existing_instance" {
  ami           = "ami-0c02fb55956c7d316"  # Replace with actual AMI
  instance_type = "t2.micro"               # Replace with actual type
  
  tags = {
    Name      = "Imported Instance"
    ManagedBy = "Terraform"
  }
}

# Resource configuration for existing VPC
resource "aws_vpc" "existing_vpc" {
  cidr_block           = "10.0.0.0/16"  # Replace with actual CIDR
  enable_dns_hostnames = true
  enable_dns_support   = true
  
  tags = {
    Name      = "Imported VPC"
    ManagedBy = "Terraform"
  }
}

# Import block (Terraform 1.5+)
import {
  to = aws_s3_bucket.imported_with_block
  id = "my-existing-bucket-2023"  # Replace with actual bucket name
}

resource "aws_s3_bucket" "imported_with_block" {
  bucket = "my-existing-bucket-2023"  # Must match import ID
  
  tags = {
    Name      = "Imported with Block"
    ManagedBy = "Terraform"
  }
}

# Generate import configuration
# Use: terraform plan -generate-config-out=generated.tf
resource "aws_iam_role" "generated_import" {
  # Configuration will be generated by Terraform
}

output "import_instructions" {
  value = {
    s3_bucket = "terraform import aws_s3_bucket.existing_bucket existing-bucket-name"
    ec2_instance = "terraform import aws_instance.existing_instance i-1234567890abcdef0"
    vpc = "terraform import aws_vpc.existing_vpc vpc-12345678"
    iam_role = "terraform import aws_iam_role.generated_import role-name"
  }
}
